kind: Secret
apiVersion: v1
metadata:
  name: pay-recorrenciagestao
  namespace: pay.ns1-d
stringData:
  dbconfig_connectionstring: Server=CADOD-DBSQLW001\\SQLDSV1;Database=DBPAYRECGES;User Id=crefisa.com.br\\USR_PAY_RECORRENCIAGESTAO_DEV;Password=<<COFRE>>;
  ecm_client_id: crefisa
  ecm_client_secret: KNo7ROBVjR7ivxXb1D8sEkHkqgnLEG0r
  ecm_token_url: https://crefisa-ods.onefinancial.com.br
  ecm_url: https://crefisa-ods.onefinancial.com.br
  redis_sentinel: "CADOH-SVCPJL001:26379","CADOH-SVCPJL002:26379", "CADOH-SVCPJL003:26379"
  redis_cluster: "CADOH-SVCPJL001:6379","CADOH-SVCPJL002:6379","CADOH-SVCPJL003:6379"
  redis_name: localhost
  redis_port: '6379'
  kafka_bootstrap_server: kafka-hmg-kafka-bootstrap.kfk-ns1-h.svc:9093
  kafka_usr: usr-ged-hmg
  kafka_usr_pass: <<COFRE>>
  jwtconfig_rsapublickey: <<COFRRE>>
type: Opaque